# Generated by Django 5.0.6 on 2024-06-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_type', models.BooleanField()),
                ('pet_age', models.IntegerField()),
                ('pet_weight', models.FloatField()),
                ('pet_sterilized', models.BooleanField()),
                ('pet_diseases', models.TextField()),
                ('pet_sex', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorisation.user')),
            ],
            options={
                'db_table': 'pets',
            },
        ),
    ]
