# Generated by Django 5.0.6 on 2024-06-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=100)),
                ('article_content', models.TextField()),
                ('article_data', models.DateField()),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
