# Generated by Django 5.0.6 on 2024-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_name', models.CharField(max_length=50)),
                ('energy_value', models.FloatField()),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'foods',
            },
        ),
    ]
